import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Richard Johnston Portfolio</title>
        <meta name="description" content="Generated by create react app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10 ">
        <section className= " min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl text-white font-bold">Hello</h1>
            <ul>
              <li>
                <BsFillMoonStarsFill/>
              </li>
              <li><a href="#">Resume</a></li>
            </ul>
          </nav>
        </section>      
      </main>
    </div>
  );
}


